name: 'Gomboc.AI Terraform Remediate Action'

description: 'Run the Gomboc.AI service against your Terraform code'

inputs:
  gomboc-config:
    description: 'Gomboc configuration file'
    required: false
    default: 'gomboc.yaml'
  working-directory:
    description: 'The directory for the Terraform configuration'
    required: false
    default: '.'
  access-token:
    description: 'Access token needed to perform API side effects'
    required: true
  action:
    description: 'Create a pull request with the remediations'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16.20.0

    - run: npm i -g https://gombocdownloads.s3.amazonaws.com/cli.tar
      shell: bash

    - name: Get OIDC token 
      id: get-oidc-token
      run: |
        echo "ID_TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | python -c "import sys, json; print(json.load(sys.stdin)['value'])")" >> $GITHUB_OUTPUT
      shell: bash

    - run: |
        gomboc terraform remediate remote ${{ inputs.action }} --auth-token ${{ steps.get-oidc-token.outputs.ID_TOKEN }} --config ${{ inputs.gomboc-config }} --working-directory ${{ inputs.working-directory }} --access-token ${{ inputs.access-token }}
      shell: bash
