name: Getting started with Gomboc AI

permissions:
  id-token: write
  contents: write
  pull-requests: write
  
on:
  pull_request:

env:
  FORCE_COLOR: 3

jobs:
  gomboc-ai:
    runs-on: ubuntu-latest
    steps:
      - uses: Gomboc-AI/actions/terraform/remediate@main
        with:
          working-directory: the-tf-directory-in-your-repo
          access-token: ${{ secrets.GITHUB_TOKEN }}
          action: direct-apply
