name: Gomboc AI - On Push

permissions:
  id-token: write
  contents: read

on:
  pull_request:

jobs:
  gomboc-ai:
    runs-on: ubuntu-latest
    steps:
      - uses: Gomboc-AI/actions/terraform/remediate@main
        with:
          action: submit-for-review
