name: 'Gomboc.AI On Schedule Action'

description: 'Secure your IaC with Gomboc.AI'

inputs:
  GOMBOC_SERVER_URL: 
    description: 'Internal use only'
    required: false
  GOMBOC_CLIENT_URL: 
    description: 'Internal use only'
    required: false
  GOMBOC_DEBUG:
    description: 'Internal use only'
    required: false
  effect:
    description: "'submit-for-review' will fail the job and create an additional PR with the remediations we have found for your submitted PR. 'audit' will allow the PR to pass the job even if there are findings available, however it will list any observations we can make."
    required: false
    default: 'submit-for-review'
    enum:
      - 'submit-for-review'
      - 'audit'
  target-directory:
    description: "The directory that contains your IaC files"
    required: true
    type: string
  iac:
    description: "A space separated list with the IaC you want us to check"
    required: true
    type: array
    items:
      type: string
      enum:
        - 'cloudformation'
        - 'terraform'
  recurse:
    description: "When set to true, Gomboc will check additional directories within the target-directory and try to remediate any IaC files found"
    required: false
    default: false
    type: boolean
  cli-version:
    description: "The specific CLI version you would like us to use"
    required: false
    default: latest
    type: string

runs:
  using: "composite"
  steps:
    - name: Handle unsupported event types
      if: github.event_name != 'schedule'
      env:
        FORCE_COLOR: 3
      run: |
        echo -e "\033[0;31mUnsupported event type: ${{ github.event_name }}. Try on:schedule\033[0m"
        exit 0
      shell: bash

    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version: 18.17.0

    - name: Get OIDC token 
      id: get-oidc-token
      run: |
        echo "ID_TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | python -c "import sys, json; print(json.load(sys.stdin)['value'])")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Handle pull_request event
      env:
        FORCE_COLOR: 3
      run: |
        docker run --rm \
          -e GOMBOC_DEBUG=${{inputs.GOMBOC_DEBUG}} \
          -e GOMBOC_SERVER_URL=${{inputs.GOMBOC_SERVER_URL}} \
          -e GOMBOC_CLIENT_URL=${{inputs.GOMBOC_CLIENT_URL}} \
          gombocai/cli:${{ inputs.cli-version }} \
          sh -c "gomboc ${{ inputs.effect }} on-schedule --auth-token ${{ steps.get-oidc-token.outputs.ID_TOKEN }} --target-directory ${{ target-directory }} --iac ${{ inputs.iac }}"

      shell: bash
